services:
  db:
    container_name: amplify_db
    image: mariadb:10.11
    ports:
      - "13306:3306"
    volumes:
      - .data/mariadb:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      # # HACK: easy sql script running for setting up db
      # - ./amplify.sql:/amplify.sql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: amplify
      MARIADB_USER: amplify
      MARIADB_PASSWORD: password
    healthcheck:
      test: mysql amplify -u amplify -ppassword -e 'SELECT 1;' || exit 1

  app: &app
    container_name: amplify_app
    # image: dhil/amplify
    build:
      context: .
      target: amplify
    ports:
      - "8080:80"
    volumes:
      # code for development
      - .:/var/www/html

      # use the container's var (for cache, etc)
      - /var/www/html/var
      # persist file uploads in .data
      - .data/app/data:/var/www/html/data
      # persist logs
      - .data/app/log:/var/www/html/var/log

      # use the container's node_modules & vendor folders (don't override)
      - /var/www/html/public/node_modules
      - /var/www/html/public/bundles
      - /var/www/html/vendor
    healthcheck:
      test: curl --fail http://localhost/health.php || exit 1
    depends_on:
      db:
        condition: service_healthy

  worker:
    <<: *app
    container_name: amplify_worker
    command: php bin/console messenger:consume async scheduled -vv
    ports: []
    healthcheck: {}
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_healthy

  docs:
    container_name: amplify_docs_watcher
    build:
      context: .
      target: amplify-docs
    command: jekyll serve
    volumes:
      - ./docs:/app
      - ./public/docs:/app/_site

  mail:
    container_name: amplify_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"