<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Person;
use Nines\UtilBundle\Form\DatalistType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Person form.
 */
class PersonType extends AbstractType {
    private static array $DEFAULT_INSTITUTIONS = [
        'Acadia University',
        'Adler Graduate Professional School Inc.',
        'Adler University - Vancouver',
        'Alberta College of Art and Design',
        'Algoma University',
        'Algonquin College',
        'Ambrose University',
        'Assiniboine Community College',
        'Athabasca University',
        'Aurora College',
        'Banff Centre for Arts and Creativity',
        "Bishop's University",
        'Bow Valley College',
        'Brandon University',
        'Brescia University College',
        'British Columbia Institute of Technology',
        'Brock University',
        'Burman University',
        'Cambrian College of Applied Arts and Technology',
        'Camosun College',
        'Campus Notre-Dame-de-Foy',
        'Canadian Mennonite University',
        'Canadore College',
        'Cape Breton University',
        'Capilano University',
        'Carleton University',
        'Cégep André Laurendeau',
        'Cégep de Drummondville',
        'Cégep de Granby',
        'Cégep de Jonquière',
        "Cégep de l'Outaouais",
        'Cégep de la Gaspésie et des îles',
        'Cégep de La Pocatière',
        'Cégep de Rivière-du-Loup',
        'Cégep de Saint-Félicien',
        'Cégep de Saint-Hyacinthe',
        'Cégep de Saint-Laurent',
        'Cégep de Sainte-Foy',
        'Cégep de Sept-Îles',
        'Cégep de Sherbrooke',
        'Cégep de Sorel-Tracy',
        'Cégep de Thetford',
        'Cégep de Trois-Rivières',
        'Cégep de Victoriaville',
        'Cégep du Vieux Montréal',
        'Cégep Édouard-Montpetit',
        'Cégep Garneau',
        'Cégep Gérald-Godin',
        'Cégep Limoilou',
        'Cégep Marie-Victorin',
        'Cégep régional de Lanaudière',
        'Cégep Saint-Jean-sur-Richelieu',
        'Centennial College',
        'Champlain Regional College',
        'Coast Mountain College',
        'Collège Boréal',
        'Collège communautaire du Nouveau-Brunswick',
        'Collège de Bois-de-Boulogne',
        'Collège de Maisonneuve',
        'Collège de Rosemont',
        'Collège de Valleyfield',
        'Collège Laflèche',
        'Collège Lionel-Groulx',
        'Collège Mérici',
        'Collège Montmorency',
        'College of New Caledonia',
        'College of the North Atlantic',
        'College of the Rockies',
        'Concordia University',
        'Concordia University of Edmonton',
        'Conestoga College Institute of Technology and Advanced Learning',
        'Confederation College',
        'Crandall University',
        'Cumberland College',
        'Dalhousie University',
        'Dawson College',
        'Dominican University College',
        'Douglas College',
        'Durham College',
        'École de technologie supérieure',
        "École nationale d'administration publique",
        'École nationale de police du Québec',
        'Emily Carr University of Art + Design',
        'Fanshawe College',
        'George Brown College',
        'Georgian College of Applied Arts and Technology',
        'Grande Prairie Regional College',
        'Grant MacEwan University',
        'HEC Montréal',
        'Holland College',
        'Humber College Institute of Technology and Advanced Learning',
        'Huron University College',
        "Institut de tourisme et d'hôtellerie du Québec",
        'Institut national de la recherche scientifique',
        'Institute for Christian Studies',
        'John Abbott College',
        'Justice Institute of British Columbia',
        "King's University College at Western University",
        'Kutenai Art Therapy Institute',
        'Kwantlen Polytechnic University',
        'La Cité collégiale',
        'Lakehead University',
        'Lakeland College',
        'Lambton College',
        'Langara College',
        'Laurentian University',
        'Lethbridge College',
        'Loyalist College of Applied Arts and Technology',
        'McGill University',
        'McMaster University',
        'Medicine Hat College',
        'Memorial University of Newfoundland',
        'Mohawk College of Applied Arts and Technology',
        'Mount Allison University',
        'Mount Royal University',
        'Mount Saint Vincent University',
        'NAIT',
        'National Circus School',
        'New Brunswick Community College',
        'Niagara College Canada',
        'Nipissing University',
        'NorQuest College',
        'North Island College',
        'Northern Alberta Institute of Technology',
        'Northern College of Applied Arts and Technology',
        'Northern Lights College',
        'Northwest Territories',
        'Nova Scotia College of Art and Design University',
        'Nova Scotia Community College',
        'Nunavut Arctic College',
        'OCAD University',
        'Okanagan College',
        'Olds College',
        'Ontario',
        'Parkland College',
        'Polytechnique Montréal',
        'Portage College',
        'Prince Edward Island',
        'Quebec',
        "Queen's University",
        'Red Deer College',
        'Red River College',
        'Redeemer University College',
        'Regent College',
        'Royal Military College of Canada',
        'Royal Roads University',
        'Ryerson University',
        "Saint Mary's University",
        'Saint Paul University',
        'Saskatchewan Polytechnic',
        'Selkirk College',
        'Seneca College for Applied Arts and Technology',
        'Sheridan College Institute of Technology and Advanced Learning',
        'Simon Fraser University',
        'Sir Sandford Fleming College of Applied Arts and Technology',
        'Southern Alberta Institute of Technology',
        'St. Clair College',
        'St. Francis Xavier University',
        'St. Lawrence College of Applied Arts and Technology',
        "St. Mary's University - Calgary",
        'St. Thomas More College',
        'St. Thomas University',
        'Télé-université',
        "The King's University (Edmonton)",
        'The University of British Columbia',
        'The University of Winnipeg',
        'Thompson Rivers University',
        'Trent University',
        'Trinity Western University',
        'Tyndale University College & Seminary',
        'Unity Health Toronto',
        'Université de Moncton',
        'Université de Montréal',
        'Université de Saint-Boniface',
        'Université de Sherbrooke',
        'Université du Québec à Chicoutimi',
        'Université du Québec à Montréal',
        'Université du Québec à Rimouski',
        'Université du Québec à Trois-Rivières',
        'Université du Québec en Abitibi-Témiscamingue',
        'Université du Québec en Outaouais',
        'Université Laval',
        'Université Sainte-Anne',
        'University Blue Quills',
        'University College London',
        'University College of the North',
        'University of Alberta',
        'University of Calgary',
        'University of Guelph',
        "University of King's College (Halifax)",
        'University of Lethbridge',
        'University of Manitoba',
        'University of New Brunswick',
        'University of Northern British Columbia',
        'University of Ontario Institute of Technology',
        'University of Ottawa',
        'University of Prince Edward Island',
        'University of Regina',
        'University of Saskatchewan',
        "University of St. Michael's College",
        'University of the Fraser Valley',
        'University of Toronto',
        'University of Victoria',
        'University of Waterloo',
        'University of Windsor',
        'Vancouver Community College',
        'Vancouver Island University',
        'Vanier College',
        'Victoria University, Toronto',
        'Western University',
        'Wilfrid Laurier University',
        'Wycliffe College',
        'York University',
        'Yukon College',
    ];

    /**
     * Add form fields to $builder.
     */
    public function buildForm(FormBuilderInterface $builder, array $options) : void {
        $builder->add('fullname', TextType::class, [
            'label' => 'Fullname',
            'required' => true,
        ]);
        $builder->add('sortableName', TextType::class, [
            'label' => 'Sortable Name',
            'required' => true,
        ]);
        $builder->add('location', TextType::class, [
            'label' => 'Location',
            'required' => true,
        ]);
        $builder->add('bio', TextareaType::class, [
            'label' => 'Bio',
            'required' => true,
            'attr' => [
                'class' => 'tinymce',
            ],
        ]);
        $builder->add('institution', DatalistType::class, [
            'label' => 'Institution',
            'required' => false,
            'datalist' => self::$DEFAULT_INSTITUTIONS,
        ]);
    }

    /**
     * Define options for the form.
     *
     * Set default, optional, and required options passed to the
     * buildForm() method via the $options parameter.
     */
    public function configureOptions(OptionsResolver $resolver) : void {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}
